version: '3'
services:
  namenode:
    image: qnib/plain-hdfs-namenode
    #hostname: '{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}'
    ports:
      - "8088:8088"
      - "50070:50070"
  datanode:
    image: qnib/plain-hdfs-datanode
    #hostname: '{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}'
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
